#Definisikan nama workflow
name: Todo App Build Test

#Setup trigger
on: 
  push: #Jalankan workflow ketika ada event push pada branch master
    branches: [ master ] 
  pull_request: #Jalankan workflow ketika ada event pull pada branch master
    branches: [ master ]
jobs:
  build_and_test: #Jalankan flow build and test dengan ubuntu versi latest
    runs-on: ubuntu-latest
    steps:
    - name: Clonning Project #Lakukan clonning project dengan action checkout
      uses: actions/checkout@v2
    - name: List files
      run : |
        ls ${{ github.workspace }} 
    - name: Setup Node.js 14 #Instalasi node js versi 14 dengan action setupnode14
      uses: actions/setup-node14@v2
      with: 
        node-version: '14'
    - name: Install project #Lakukan instalasi project
      run: npm install
    - name: Test project
      run: npm test
